import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();
const PayItemSchema = z.object({ code: z.string(), description: z.string(), unit: z.string(), unitPrice: z.number().nonnegative() });

const PayItemsExportArgs = z.object({ action: z.literal("pay_items_export"), outputPath: z.string(), corridorName: z.string().optional(), baseSurface: z.string().optional(), designSurface: z.string().optional(), alignmentName: z.string().optional(), payItems: z.array(PayItemSchema).optional(), includeEarthwork: z.boolean().optional(), includeCorridorMaterials: z.boolean().optional(), includePipeLengths: z.boolean().optional(), includeStructureCounts: z.boolean().optional() });
const MaterialCostEstimateArgs = z.object({ action: z.literal("material_cost_estimate"), corridorName: z.string().optional(), baseSurface: z.string().optional(), designSurface: z.string().optional(), alignmentName: z.string().optional(), contingencyPercent: z.number().nonnegative().optional(), mobilizationPercent: z.number().nonnegative().optional(), payItems: z.array(PayItemSchema), outputPath: z.string().optional() });

export const COST_ESTIMATION_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "cost_estimation",
  actions: {
    pay_items_export: { action: "pay_items_export", inputSchema: PayItemsExportArgs, responseSchema: GenericResponseSchema, capabilities: ["export", "generate"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["exportPayItems"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("exportPayItems", { outputPath: args.outputPath, corridorName: args.corridorName ?? null, baseSurface: args.baseSurface ?? null, designSurface: args.designSurface ?? null, alignmentName: args.alignmentName ?? null, payItems: args.payItems ?? [], includeEarthwork: args.includeEarthwork ?? true, includeCorridorMaterials: args.includeCorridorMaterials ?? true, includePipeLengths: args.includePipeLengths ?? true, includeStructureCounts: args.includeStructureCounts ?? true })) },
    material_cost_estimate: { action: "material_cost_estimate", inputSchema: MaterialCostEstimateArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze", "generate"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["calculateMaterialCostEstimate"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("calculateMaterialCostEstimate", { corridorName: args.corridorName ?? null, baseSurface: args.baseSurface ?? null, designSurface: args.designSurface ?? null, alignmentName: args.alignmentName ?? null, contingencyPercent: args.contingencyPercent ?? 0, mobilizationPercent: args.mobilizationPercent ?? 5, payItems: args.payItems, outputPath: args.outputPath ?? null })) },
  },
  exposures: [
    { toolName: "civil3d_cost_estimation", displayName: "Civil 3D Cost Estimation", description: "Exports pay items and calculates material cost estimates through a single domain tool.", inputShape: { action: z.enum(["pay_items_export", "material_cost_estimate"]), outputPath: z.string().optional(), corridorName: z.string().optional(), baseSurface: z.string().optional(), designSurface: z.string().optional(), alignmentName: z.string().optional(), payItems: z.array(PayItemSchema).optional(), includeEarthwork: z.boolean().optional(), includeCorridorMaterials: z.boolean().optional(), includePipeLengths: z.boolean().optional(), includeStructureCounts: z.boolean().optional(), contingencyPercent: z.number().optional(), mobilizationPercent: z.number().optional() }, supportedActions: ["pay_items_export", "material_cost_estimate"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_pay_items_export", displayName: "Civil 3D Pay Items Export", description: "Exports pay-item schedules and quantities.", inputShape: { outputPath: z.string(), corridorName: z.string().optional(), baseSurface: z.string().optional(), designSurface: z.string().optional(), alignmentName: z.string().optional(), payItems: z.array(PayItemSchema).optional(), includeEarthwork: z.boolean().optional(), includeCorridorMaterials: z.boolean().optional(), includePipeLengths: z.boolean().optional(), includeStructureCounts: z.boolean().optional() }, supportedActions: ["pay_items_export"], resolveAction: (rawArgs) => ({ action: "pay_items_export", args: { action: "pay_items_export", ...rawArgs } }) },
    { toolName: "civil3d_material_cost_estimate", displayName: "Civil 3D Material Cost Estimate", description: "Calculates a construction cost estimate from Civil 3D quantities and pay items.", inputShape: { corridorName: z.string().optional(), baseSurface: z.string().optional(), designSurface: z.string().optional(), alignmentName: z.string().optional(), contingencyPercent: z.number().nonnegative().optional(), mobilizationPercent: z.number().nonnegative().optional(), payItems: z.array(PayItemSchema), outputPath: z.string().optional() }, supportedActions: ["material_cost_estimate"], resolveAction: (rawArgs) => ({ action: "material_cost_estimate", args: { action: "material_cost_estimate", ...rawArgs } }) },
  ],
};
