import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();

const DetentionBasinSizeArgs = z.object({ action: z.literal("basin_size_calculate"), inflow: z.number().positive(), outflow: z.number().positive(), stormDuration: z.number().positive().optional(), method: z.enum(["modified_rational", "triangular_hydrograph", "scs_curve_number"]).optional(), sideSlope: z.number().positive().optional(), bottomWidth: z.number().nonnegative().optional(), freeboardDepth: z.number().nonnegative().optional(), surfaceName: z.string().optional() });
const DetentionStageStorageArgs = z.object({ action: z.literal("stage_storage"), surfaceName: z.string(), bottomElevation: z.number(), topElevation: z.number(), elevationIncrement: z.number().positive().optional(), outletType: z.enum(["orifice", "weir", "riser"]).optional(), outletDiameter: z.number().positive().optional(), weirLength: z.number().positive().optional(), dischargeCoefficient: z.number().positive().optional() });

export const DETENTION_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "detention",
  actions: {
    basin_size_calculate: { action: "basin_size_calculate", inputSchema: DetentionBasinSizeArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["calculateDetentionBasinSize"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("calculateDetentionBasinSize", { inflow: args.inflow, outflow: args.outflow, stormDuration: args.stormDuration ?? 60, method: args.method ?? "modified_rational", sideSlope: args.sideSlope ?? 3.0, bottomWidth: args.bottomWidth ?? 10.0, freeboardDepth: args.freeboardDepth ?? 1.0, surfaceName: args.surfaceName ?? null })) },
    stage_storage: { action: "stage_storage", inputSchema: DetentionStageStorageArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze", "generate"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["calculateDetentionStageStorage"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("calculateDetentionStageStorage", { surfaceName: args.surfaceName, bottomElevation: args.bottomElevation, topElevation: args.topElevation, elevationIncrement: args.elevationIncrement ?? 0.5, outletType: args.outletType ?? "orifice", outletDiameter: args.outletDiameter ?? null, weirLength: args.weirLength ?? null, dischargeCoefficient: args.dischargeCoefficient ?? null })) },
  },
  exposures: [
    { toolName: "civil3d_detention", displayName: "Civil 3D Detention", description: "Calculates detention basin sizing and stage-storage workflows through a single domain tool.", inputShape: { action: z.enum(["basin_size_calculate", "stage_storage"]), inflow: z.number().optional(), outflow: z.number().optional(), stormDuration: z.number().optional(), method: z.enum(["modified_rational", "triangular_hydrograph", "scs_curve_number"]).optional(), sideSlope: z.number().optional(), bottomWidth: z.number().optional(), freeboardDepth: z.number().optional(), surfaceName: z.string().optional(), bottomElevation: z.number().optional(), topElevation: z.number().optional(), elevationIncrement: z.number().optional(), outletType: z.enum(["orifice", "weir", "riser"]).optional(), outletDiameter: z.number().optional(), weirLength: z.number().optional(), dischargeCoefficient: z.number().optional() }, supportedActions: ["basin_size_calculate", "stage_storage"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_detention_basin_size_calculate", displayName: "Civil 3D Detention Basin Size Calculate", description: "Calculates detention basin size requirements.", inputShape: { inflow: z.number().positive(), outflow: z.number().positive(), stormDuration: z.number().positive().optional(), method: z.enum(["modified_rational", "triangular_hydrograph", "scs_curve_number"]).optional(), sideSlope: z.number().positive().optional(), bottomWidth: z.number().nonnegative().optional(), freeboardDepth: z.number().nonnegative().optional(), surfaceName: z.string().optional() }, supportedActions: ["basin_size_calculate"], resolveAction: (rawArgs) => ({ action: "basin_size_calculate", args: { action: "basin_size_calculate", ...rawArgs } }) },
    { toolName: "civil3d_detention_stage_storage", displayName: "Civil 3D Detention Stage Storage", description: "Generates stage-storage-discharge output for a detention basin surface.", inputShape: { surfaceName: z.string(), bottomElevation: z.number(), topElevation: z.number(), elevationIncrement: z.number().positive().optional(), outletType: z.enum(["orifice", "weir", "riser"]).optional(), outletDiameter: z.number().positive().optional(), weirLength: z.number().positive().optional(), dischargeCoefficient: z.number().positive().optional() }, supportedActions: ["stage_storage"], resolveAction: (rawArgs) => ({ action: "stage_storage", args: { action: "stage_storage", ...rawArgs } }) },
  ],
};
