import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();
const Point2DSchema = z.object({ x: z.number(), y: z.number() });
const Point3DSchema = z.object({ x: z.number(), y: z.number(), z: z.number() });
const CourseSchema = z.object({ bearingDegrees: z.number(), distance: z.number().positive(), slope: z.number().optional(), description: z.string().optional() });

const CogoInverseArgs = z.object({ action: z.literal("cogo_inverse"), x1: z.number(), y1: z.number(), x2: z.number(), y2: z.number() });
const CogoDirectionDistanceArgs = z.object({ action: z.literal("cogo_direction_distance"), fromX: z.number(), fromY: z.number(), fromZ: z.number().optional(), bearingDegrees: z.number(), distance: z.number().positive(), slope: z.number().optional() });
const CogoTraverseArgs = z.object({ action: z.literal("cogo_traverse"), startX: z.number(), startY: z.number(), startZ: z.number().optional(), courses: z.array(CourseSchema).min(1), isClosed: z.boolean().optional() });
const CogoCurveSolveArgs = z.object({ action: z.literal("cogo_curve_solve"), radius: z.number().positive().optional(), deltaDegrees: z.number().positive().optional(), length: z.number().positive().optional(), tangent: z.number().positive().optional(), chord: z.number().positive().optional() });
const CreateLineSegmentArgs = z.object({ action: z.literal("create_line_segment"), startX: z.number(), startY: z.number(), startZ: z.number().optional(), endX: z.number(), endY: z.number(), endZ: z.number().optional() });
const CreatePolylineArgs = z.object({ action: z.literal("create_polyline"), points: z.array(Point2DSchema).min(2), closed: z.boolean().optional(), layer: z.string().optional() });
const Create3dPolylineArgs = z.object({ action: z.literal("create_3dpolyline"), points: z.array(Point3DSchema).min(2), closed: z.boolean().optional(), layer: z.string().optional() });
const CreateTextArgs = z.object({ action: z.literal("create_text"), text: z.string().min(1), x: z.number(), y: z.number(), z: z.number().optional(), height: z.number().positive().optional(), rotation: z.number().optional(), layer: z.string().optional() });
const CreateMTextArgs = z.object({ action: z.literal("create_mtext"), text: z.string().min(1), x: z.number(), y: z.number(), z: z.number().optional(), width: z.number().positive().optional(), textHeight: z.number().positive().optional(), rotation: z.number().optional(), layer: z.string().optional() });

export const GEOMETRY_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "geometry",
  actions: {
    cogo_inverse: { action: "cogo_inverse", inputSchema: CogoInverseArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["cogoInverse"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("cogoInverse", { x1: args.x1, y1: args.y1, x2: args.x2, y2: args.y2 })) },
    cogo_direction_distance: { action: "cogo_direction_distance", inputSchema: CogoDirectionDistanceArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["cogoDirectionDistance"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("cogoDirectionDistance", { fromX: args.fromX, fromY: args.fromY, fromZ: args.fromZ ?? 0, bearingDegrees: args.bearingDegrees, distance: args.distance, slope: args.slope ?? null })) },
    cogo_traverse: { action: "cogo_traverse", inputSchema: CogoTraverseArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["cogoTraverse"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("cogoTraverse", { startX: args.startX, startY: args.startY, startZ: args.startZ ?? 0, courses: args.courses, isClosed: args.isClosed ?? false })) },
    cogo_curve_solve: { action: "cogo_curve_solve", inputSchema: CogoCurveSolveArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["cogoCurveSolve"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("cogoCurveSolve", { radius: args.radius ?? null, deltaDegrees: args.deltaDegrees ?? null, length: args.length ?? null, tangent: args.tangent ?? null, chord: args.chord ?? null })) },
    create_line_segment: { action: "create_line_segment", inputSchema: CreateLineSegmentArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["createLineSegment"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("createLineSegment", { startX: args.startX, startY: args.startY, startZ: args.startZ, endX: args.endX, endY: args.endY, endZ: args.endZ })) },
    create_polyline: { action: "create_polyline", inputSchema: CreatePolylineArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["createPolyline"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("createPolyline", { points: args.points, closed: args.closed ? 1 : 0, layer: args.layer })) },
    create_3dpolyline: { action: "create_3dpolyline", inputSchema: Create3dPolylineArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["create3dPolyline"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("create3dPolyline", { points: args.points, closed: args.closed ? 1 : 0, layer: args.layer })) },
    create_text: { action: "create_text", inputSchema: CreateTextArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["createText"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("createText", { text: args.text, x: args.x, y: args.y, z: args.z, height: args.height, rotation: args.rotation, layer: args.layer })) },
    create_mtext: { action: "create_mtext", inputSchema: CreateMTextArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["createMText"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("createMText", { text: args.text, x: args.x, y: args.y, z: args.z, width: args.width, textHeight: args.textHeight, rotation: args.rotation, layer: args.layer })) },
  },
  exposures: [
    { toolName: "civil3d_geometry", displayName: "Civil 3D Geometry", description: "Runs COGO calculations and basic drafting geometry creation through a single domain tool.", inputShape: { action: z.enum(["cogo_inverse", "cogo_direction_distance", "cogo_traverse", "cogo_curve_solve", "create_line_segment", "create_polyline", "create_3dpolyline", "create_text", "create_mtext"]), x1: z.number().optional(), y1: z.number().optional(), x2: z.number().optional(), y2: z.number().optional(), fromX: z.number().optional(), fromY: z.number().optional(), fromZ: z.number().optional(), bearingDegrees: z.number().optional(), distance: z.number().optional(), slope: z.number().optional(), startX: z.number().optional(), startY: z.number().optional(), startZ: z.number().optional(), courses: z.array(CourseSchema).optional(), isClosed: z.boolean().optional(), radius: z.number().optional(), deltaDegrees: z.number().optional(), length: z.number().optional(), tangent: z.number().optional(), chord: z.number().optional(), endX: z.number().optional(), endY: z.number().optional(), endZ: z.number().optional(), points: z.array(z.union([Point2DSchema, Point3DSchema])).optional(), closed: z.boolean().optional(), layer: z.string().optional(), text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), z: z.number().optional(), height: z.number().optional(), rotation: z.number().optional(), width: z.number().optional(), textHeight: z.number().optional() }, supportedActions: ["cogo_inverse", "cogo_direction_distance", "cogo_traverse", "cogo_curve_solve", "create_line_segment", "create_polyline", "create_3dpolyline", "create_text", "create_mtext"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_cogo_inverse", displayName: "Civil 3D COGO Inverse", description: "Calculates bearing and distance between two coordinates.", inputShape: { x1: z.number(), y1: z.number(), x2: z.number(), y2: z.number() }, supportedActions: ["cogo_inverse"], resolveAction: (rawArgs) => ({ action: "cogo_inverse", args: { action: "cogo_inverse", ...rawArgs } }) },
    { toolName: "civil3d_cogo_direction_distance", displayName: "Civil 3D COGO Direction Distance", description: "Projects a point from bearing and distance.", inputShape: { fromX: z.number(), fromY: z.number(), fromZ: z.number().optional(), bearingDegrees: z.number(), distance: z.number().positive(), slope: z.number().optional() }, supportedActions: ["cogo_direction_distance"], resolveAction: (rawArgs) => ({ action: "cogo_direction_distance", args: { action: "cogo_direction_distance", ...rawArgs } }) },
    { toolName: "civil3d_cogo_traverse", displayName: "Civil 3D COGO Traverse", description: "Solves a traverse from courses.", inputShape: { startX: z.number(), startY: z.number(), startZ: z.number().optional(), courses: z.array(CourseSchema).min(1), isClosed: z.boolean().optional() }, supportedActions: ["cogo_traverse"], resolveAction: (rawArgs) => ({ action: "cogo_traverse", args: { action: "cogo_traverse", ...rawArgs } }) },
    { toolName: "civil3d_cogo_curve_solve", displayName: "Civil 3D COGO Curve Solve", description: "Solves a horizontal curve from known elements.", inputShape: { radius: z.number().positive().optional(), deltaDegrees: z.number().positive().optional(), length: z.number().positive().optional(), tangent: z.number().positive().optional(), chord: z.number().positive().optional() }, supportedActions: ["cogo_curve_solve"], resolveAction: (rawArgs) => ({ action: "cogo_curve_solve", args: { action: "cogo_curve_solve", ...rawArgs } }) },
    { toolName: "create_line_segment", displayName: "Create Line Segment", description: "Creates a line segment in the drawing.", inputShape: { startX: z.number(), startY: z.number(), startZ: z.number().optional(), endX: z.number(), endY: z.number(), endZ: z.number().optional() }, supportedActions: ["create_line_segment"], resolveAction: (rawArgs) => ({ action: "create_line_segment", args: { action: "create_line_segment", ...rawArgs } }) },
    { toolName: "acad_create_polyline", displayName: "AutoCAD Create Polyline", description: "Creates a 2D polyline in model space.", inputShape: { points: z.array(Point2DSchema).min(2), closed: z.boolean().optional(), layer: z.string().optional() }, supportedActions: ["create_polyline"], resolveAction: (rawArgs) => ({ action: "create_polyline", args: { action: "create_polyline", ...rawArgs } }) },
    { toolName: "acad_create_3dpolyline", displayName: "AutoCAD Create 3D Polyline", description: "Creates a 3D polyline in model space.", inputShape: { points: z.array(Point3DSchema).min(2), closed: z.boolean().optional(), layer: z.string().optional() }, supportedActions: ["create_3dpolyline"], resolveAction: (rawArgs) => ({ action: "create_3dpolyline", args: { action: "create_3dpolyline", ...rawArgs } }) },
    { toolName: "acad_create_text", displayName: "AutoCAD Create Text", description: "Creates DBText in model space.", inputShape: { text: z.string().min(1), x: z.number(), y: z.number(), z: z.number().optional(), height: z.number().positive().optional(), rotation: z.number().optional(), layer: z.string().optional() }, supportedActions: ["create_text"], resolveAction: (rawArgs) => ({ action: "create_text", args: { action: "create_text", ...rawArgs } }) },
    { toolName: "acad_create_mtext", displayName: "AutoCAD Create MText", description: "Creates MText in model space.", inputShape: { text: z.string().min(1), x: z.number(), y: z.number(), z: z.number().optional(), width: z.number().positive().optional(), textHeight: z.number().positive().optional(), rotation: z.number().optional(), layer: z.string().optional() }, supportedActions: ["create_mtext"], resolveAction: (rawArgs) => ({ action: "create_mtext", args: { action: "create_mtext", ...rawArgs } }) },
  ],
};
