import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();

const IntersectionListArgs = z.object({ action: z.literal("list"), siteName: z.string().optional() });
const IntersectionCreateArgs = z.object({ action: z.literal("create"), name: z.string(), mainRoadAlignment: z.string(), mainRoadProfile: z.string(), intersectingRoadAlignment: z.string(), intersectingRoadProfile: z.string(), intersectionPoint: z.tuple([z.number(), z.number()]).optional(), siteName: z.string().optional(), offsetDistance: z.number().nonnegative().optional(), curveRadius: z.number().nonnegative().optional(), createCorridors: z.boolean().optional(), mainRoadAssembly: z.string().optional(), intersectingRoadAssembly: z.string().optional() });
const IntersectionGetArgs = z.object({ action: z.literal("get"), name: z.string(), includeCorridorInfo: z.boolean().optional(), includeCurbReturns: z.boolean().optional() });

export const INTERSECTION_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "alignment",
  actions: {
    list: { action: "list", inputSchema: IntersectionListArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "inspect"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["listIntersections"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("listIntersections", { siteName: args.siteName ?? null })) },
    create: { action: "create", inputSchema: IntersectionCreateArgs, responseSchema: GenericResponseSchema, capabilities: ["create"], requiresActiveDrawing: true, safeForRetry: false, pluginMethods: ["createIntersection"], execute: async (args) => await withApplicationConnection(async (appClient) => { const point = args.intersectionPoint as [number, number] | undefined; return await appClient.sendCommand("createIntersection", { name: args.name, mainRoadAlignment: args.mainRoadAlignment, mainRoadProfile: args.mainRoadProfile, intersectingRoadAlignment: args.intersectingRoadAlignment, intersectingRoadProfile: args.intersectingRoadProfile, intersectionX: point ? point[0] : null, intersectionY: point ? point[1] : null, siteName: args.siteName ?? null, offsetDistance: args.offsetDistance ?? null, curveRadius: args.curveRadius ?? null, createCorridors: args.createCorridors ?? false, mainRoadAssembly: args.mainRoadAssembly ?? null, intersectingRoadAssembly: args.intersectingRoadAssembly ?? null }); }) },
    get: { action: "get", inputSchema: IntersectionGetArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "inspect"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["getIntersection"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("getIntersection", { name: args.name, includeCorridorInfo: args.includeCorridorInfo ?? false, includeCurbReturns: args.includeCurbReturns ?? false })) },
  },
  exposures: [
    { toolName: "civil3d_intersection", displayName: "Civil 3D Intersection", description: "Lists, creates, and inspects Civil 3D intersections through a single domain tool.", inputShape: { action: z.enum(["list", "create", "get"]), siteName: z.string().optional(), name: z.string().optional(), mainRoadAlignment: z.string().optional(), mainRoadProfile: z.string().optional(), intersectingRoadAlignment: z.string().optional(), intersectingRoadProfile: z.string().optional(), intersectionPoint: z.tuple([z.number(), z.number()]).optional(), offsetDistance: z.number().optional(), curveRadius: z.number().optional(), createCorridors: z.boolean().optional(), mainRoadAssembly: z.string().optional(), intersectingRoadAssembly: z.string().optional(), includeCorridorInfo: z.boolean().optional(), includeCurbReturns: z.boolean().optional() }, supportedActions: ["list", "create", "get"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_intersection_list", displayName: "Civil 3D Intersection List", description: "Lists intersections in the active drawing.", inputShape: { siteName: z.string().optional() }, supportedActions: ["list"], resolveAction: (rawArgs) => ({ action: "list", args: { action: "list", ...rawArgs } }) },
    { toolName: "civil3d_intersection_create", displayName: "Civil 3D Intersection Create", description: "Creates an intersection between two alignments.", inputShape: { name: z.string(), mainRoadAlignment: z.string(), mainRoadProfile: z.string(), intersectingRoadAlignment: z.string(), intersectingRoadProfile: z.string(), intersectionPoint: z.tuple([z.number(), z.number()]).optional(), siteName: z.string().optional(), offsetDistance: z.number().nonnegative().optional(), curveRadius: z.number().nonnegative().optional(), createCorridors: z.boolean().optional(), mainRoadAssembly: z.string().optional(), intersectingRoadAssembly: z.string().optional() }, supportedActions: ["create"], resolveAction: (rawArgs) => ({ action: "create", args: { action: "create", ...rawArgs } }) },
    { toolName: "civil3d_intersection_get", displayName: "Civil 3D Intersection Get", description: "Gets detailed intersection properties.", inputShape: { name: z.string(), includeCorridorInfo: z.boolean().optional(), includeCurbReturns: z.boolean().optional() }, supportedActions: ["get"], resolveAction: (rawArgs) => ({ action: "get", args: { action: "get", ...rawArgs } }) },
  ],
};
