import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const GenericResponseSchema = z.object({}).passthrough();

const SightDistanceCalculateArgs = z.object({ action: z.literal("calculate"), designSpeed: z.number().positive(), speedUnits: z.enum(["kmh", "mph"]).optional(), sightDistanceType: z.enum(["stopping", "passing", "decision"]), grade: z.number().optional(), frictionCoefficient: z.number().positive().optional(), perceptionReactionTime: z.number().positive().optional(), standard: z.enum(["AASHTO", "FHWA", "HCM"]).optional(), alignmentName: z.string().optional(), profileName: z.string().optional(), checkStation: z.number().optional() });
const StoppingDistanceCheckArgs = z.object({ action: z.literal("stopping_distance_check"), alignmentName: z.string(), profileName: z.string(), designSpeed: z.number().positive(), stationStart: z.number().optional(), stationEnd: z.number().optional(), stationInterval: z.number().positive().optional(), standard: z.enum(["AASHTO", "FHWA"]).optional() });

export const SIGHT_DISTANCE_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "sight_distance",
  actions: {
    calculate: { action: "calculate", inputSchema: SightDistanceCalculateArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["calculateSightDistance"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("calculateSightDistance", { designSpeed: args.designSpeed, speedUnits: args.speedUnits ?? "kmh", sightDistanceType: args.sightDistanceType, grade: args.grade ?? 0, frictionCoefficient: args.frictionCoefficient ?? null, perceptionReactionTime: args.perceptionReactionTime ?? 2.5, standard: args.standard ?? "AASHTO", alignmentName: args.alignmentName ?? null, profileName: args.profileName ?? null, checkStation: args.checkStation ?? null })) },
    stopping_distance_check: { action: "stopping_distance_check", inputSchema: StoppingDistanceCheckArgs, responseSchema: GenericResponseSchema, capabilities: ["query", "analyze"], requiresActiveDrawing: true, safeForRetry: true, pluginMethods: ["checkStoppingDistance"], execute: async (args) => await withApplicationConnection(async (appClient) => await appClient.sendCommand("checkStoppingDistance", { alignmentName: args.alignmentName, profileName: args.profileName, designSpeed: args.designSpeed, stationStart: args.stationStart ?? null, stationEnd: args.stationEnd ?? null, stationInterval: args.stationInterval ?? 25, standard: args.standard ?? "AASHTO" })) },
  },
  exposures: [
    { toolName: "civil3d_sight_distance", displayName: "Civil 3D Sight Distance", description: "Calculates and checks sight distance compliance through a single domain tool.", inputShape: { action: z.enum(["calculate", "stopping_distance_check"]), designSpeed: z.number().optional(), speedUnits: z.enum(["kmh", "mph"]).optional(), sightDistanceType: z.enum(["stopping", "passing", "decision"]).optional(), grade: z.number().optional(), frictionCoefficient: z.number().optional(), perceptionReactionTime: z.number().optional(), standard: z.enum(["AASHTO", "FHWA", "HCM"]).optional(), alignmentName: z.string().optional(), profileName: z.string().optional(), checkStation: z.number().optional(), stationStart: z.number().optional(), stationEnd: z.number().optional(), stationInterval: z.number().optional() }, supportedActions: ["calculate", "stopping_distance_check"], resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }) },
    { toolName: "civil3d_sight_distance_calculate", displayName: "Civil 3D Sight Distance Calculate", description: "Calculates required sight distance.", inputShape: { designSpeed: z.number().positive(), speedUnits: z.enum(["kmh", "mph"]).optional(), sightDistanceType: z.enum(["stopping", "passing", "decision"]), grade: z.number().optional(), frictionCoefficient: z.number().positive().optional(), perceptionReactionTime: z.number().positive().optional(), standard: z.enum(["AASHTO", "FHWA", "HCM"]).optional(), alignmentName: z.string().optional(), profileName: z.string().optional(), checkStation: z.number().optional() }, supportedActions: ["calculate"], resolveAction: (rawArgs) => ({ action: "calculate", args: { action: "calculate", ...rawArgs } }) },
    { toolName: "civil3d_stopping_distance_check", displayName: "Civil 3D Stopping Distance Check", description: "Checks stopping sight distance along an alignment/profile.", inputShape: { alignmentName: z.string(), profileName: z.string(), designSpeed: z.number().positive(), stationStart: z.number().optional(), stationEnd: z.number().optional(), stationInterval: z.number().positive().optional(), standard: z.enum(["AASHTO", "FHWA"]).optional() }, supportedActions: ["stopping_distance_check"], resolveAction: (rawArgs) => ({ action: "stopping_distance_check", args: { action: "stopping_distance_check", ...rawArgs } }) },
  ],
};
