export type ToolDomain =
  | "drawing"
  | "geometry"
  | "grading"
  | "point"
  | "surface"
  | "alignment"
  | "profile"
  | "corridor"
  | "section"
  | "pipe"
  | "parcel"
  | "quantity_takeoff"
  | "qc"
  | "labeling"
  | "coordinate_system"
  | "data_shortcut"
  | "assembly"
  | "feature_line"
  | "style"
  | "job"
  | "hydrology"
  | "sight_distance"
  | "detention"
  | "slope_analysis"
  | "cost_estimation"
  | "survey"
  | "plan_production"
  | "docs"
  | "catchment"
  | "stm"
  | "plugin";

export type ToolCapability =
  | "query"
  | "create"
  | "edit"
  | "delete"
  | "analyze"
  | "manage"
  | "generate"
  | "register"
  | "inspect"
  | "export"
  | "import";

export interface ToolCatalogEntry {
  toolName: string;
  displayName: string;
  description: string;
  domain: ToolDomain;
  capabilities: ToolCapability[];
  operations?: string[];
  pluginMethods?: string[];
  requiresActiveDrawing: boolean;
  safeForRetry: boolean;
  status: "implemented" | "planned";
}

export const TOOL_CATALOG: ToolCatalogEntry[] = [
  {
    toolName: "civil3d_health",
    displayName: "Civil 3D Health",
    description: "Reports connection and plugin runtime health.",
    domain: "plugin",
    capabilities: ["inspect", "query"],
    pluginMethods: ["getCivil3DHealth"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_drawing",
    displayName: "Civil 3D Drawing",
    description: "Reads and manages drawing state, settings, save, undo, redo, and new drawing creation.",
    domain: "drawing",
    capabilities: ["query", "create", "manage"],
    operations: ["info", "settings", "new", "save", "undo", "redo"],
    pluginMethods: ["getDrawingInfo", "getDrawingSettings", "newDrawing", "saveDrawing", "undoDrawing", "redoDrawing"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "get_drawing_info",
    displayName: "Get Drawing Info",
    description: "Returns basic drawing information.",
    domain: "drawing",
    capabilities: ["query", "inspect"],
    pluginMethods: ["getDrawingInfo"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "list_civil_object_types",
    displayName: "List Civil Object Types",
    description: "Lists major Civil 3D object types available in the current context.",
    domain: "docs",
    capabilities: ["query", "inspect"],
    pluginMethods: ["listCivilObjectTypes"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "list_tool_capabilities",
    displayName: "List Tool Capabilities",
    description: "Lists domain and capability metadata for the Civil 3D MCP tool catalog, including implemented and planned tools.",
    domain: "docs",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "get_selected_civil_objects_info",
    displayName: "Get Selected Civil Objects Info",
    description: "Returns information about currently selected Civil 3D objects.",
    domain: "drawing",
    capabilities: ["query", "inspect"],
    pluginMethods: ["getSelectedCivilObjectsInfo"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment",
    displayName: "Civil 3D Alignment",
    description: "Lists, inspects, creates, deletes, and maps stations for alignments.",
    domain: "alignment",
    capabilities: ["query", "create", "delete", "analyze"],
    operations: ["list", "get", "station_to_point", "point_to_station", "create", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_report",
    displayName: "Civil 3D Alignment Report",
    description: "Builds a structured alignment report by fetching alignment geometry and sampling station locations.",
    domain: "alignment",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["getAlignment", "alignmentStationToPoint"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_add_tangent",
    displayName: "Civil 3D Alignment Add Tangent",
    description: "Appends a fixed tangent (straight line) entity to a Civil 3D alignment using two end points.",
    domain: "alignment",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_network_hgl_calculate",
    displayName: "Civil 3D Pipe Network HGL Calculate",
    description: "Calculate the Hydraulic Grade Line (HGL) and Energy Grade Line (EGL) for a Civil 3D gravity pipe network. Performs backwater analysis from the outlet upstream, reporting HGL elevation, pipe full/partial flow status, and surcharged structures at each node. Use before completing any stormwater drainage design.",
    domain: "pipe",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_hydraulic_analysis",
    displayName: "Civil 3D Pipe Hydraulic Analysis",
    description: "Run a full hydraulic capacity analysis on a Civil 3D gravity pipe network using Manning's equation. Reports pipe capacity (CFS), design flow vs capacity ratio, flow velocity, Froude number, and flags cover violations, low-velocity sedimentation risk, and high-velocity erosion risk for every pipe. Returns a per-pipe and per-structure summary.",
    domain: "pipe",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_structure_properties",
    displayName: "Civil 3D Pipe Structure Properties",
    description: "Retrieve detailed properties of a single structure (manhole, inlet, headwall, junction) in a Civil 3D gravity pipe network. Returns rim elevation, sump elevation, barrel count, connected pipe inverts, structure depth, and hydraulic head loss coefficient.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_network_size",
    displayName: "Civil 3D Pipe Network Size",
    description: "Sizes gravity-network pipes from Manning full-flow capacity, selects matching catalog parts, and can optionally apply the selected sizes back to the drawing.",
    domain: "pipe",
    capabilities: ["analyze", "edit", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_profile_view_automation",
    displayName: "Civil 3D Pipe Profile View Automation",
    description: "Automates gravity-pipe profile-view setup by resolving the network alignment and surface, creating a surface profile if needed, and creating the profile view with optional style and band set.",
    domain: "pipe",
    capabilities: ["create", "manage", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_add_curve",
    displayName: "Civil 3D Alignment Add Curve",
    description: "Appends a fixed horizontal curve entity to a Civil 3D alignment using a pass-through point and radius.",
    domain: "alignment",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_add_spiral",
    displayName: "Civil 3D Alignment Add Spiral",
    description: "Appends a spiral (transition curve) entity to a Civil 3D alignment. Clothoid, cubic, and biquadratic spiral types are supported.",
    domain: "alignment",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_delete_entity",
    displayName: "Civil 3D Alignment Delete Entity",
    description: "Deletes a single entity (tangent, curve, or spiral) from a Civil 3D alignment by its zero-based index.",
    domain: "alignment",
    capabilities: ["edit", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_set_station_equation",
    displayName: "Civil 3D Alignment Set Station Equation",
    description: "Adds a station equation to a Civil 3D alignment, allowing the nominal (displayed) station to differ from the raw measured station.",
    domain: "alignment",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_get_station_offset",
    displayName: "Civil 3D Alignment Get Station Offset",
    description: "Returns the station, offset, and perpendicular distance of an arbitrary XY point relative to a Civil 3D alignment. High-value sampling tool for AI geometry reasoning.",
    domain: "alignment",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_offset_create",
    displayName: "Civil 3D Alignment Offset Create",
    description: "Creates a new offset alignment at a constant distance from an existing base alignment. Positive offset = right side; negative = left.",
    domain: "alignment",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_alignment_widen_transition",
    displayName: "Civil 3D Alignment Widen Transition",
    description: "Creates a variable-offset (widening/narrowing) transition region on a Civil 3D alignment between two stations. Useful for modelling lane tapers and turn lanes.",
    domain: "alignment",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile",
    displayName: "Civil 3D Profile",
    description: "Lists, inspects, samples, creates, and deletes profiles.",
    domain: "profile",
    capabilities: ["query", "create", "delete", "analyze"],
    operations: ["list", "get", "get_elevation", "sample_elevations", "create_from_surface", "create_layout", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_report",
    displayName: "Civil 3D Profile Report",
    description: "Builds a structured profile report from profile detail and sampled elevations.",
    domain: "profile",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["getProfile", "sampleProfileElevations"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_add_pvi",
    displayName: "Civil 3D Profile Add PVI",
    description: "Adds a PVI (Point of Vertical Intersection) to a Civil 3D layout profile at the specified station and elevation.",
    domain: "profile",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_delete_pvi",
    displayName: "Civil 3D Profile Delete PVI",
    description: "Deletes the PVI nearest to the specified station from a Civil 3D layout profile.",
    domain: "profile",
    capabilities: ["edit", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_add_curve",
    displayName: "Civil 3D Profile Add Curve",
    description: "Adds a symmetric or asymmetric parabolic vertical curve at an existing PVI in a Civil 3D layout profile.",
    domain: "profile",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_set_grade",
    displayName: "Civil 3D Profile Set Grade",
    description: "Sets the grade (slope) of a tangent entity in a Civil 3D layout profile. Grade is expressed as a decimal fraction (0.02 = 2%).",
    domain: "profile",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_get_elevation",
    displayName: "Civil 3D Profile Get Elevation",
    description: "Samples the elevation and instantaneous grade of a Civil 3D profile at a given station. High-value tool for AI geometric reasoning.",
    domain: "profile",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_check_k_values",
    displayName: "Civil 3D Profile Check K Values",
    description: "Validates the K value of every vertical curve in a Civil 3D layout profile against AASHTO minimum K values for the specified design speed. Returns a pass/fail report per curve.",
    domain: "profile",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_view_create",
    displayName: "Civil 3D Profile View Create",
    description: "Creates a Civil 3D profile view at the specified insertion point in model space. Optionally applies a style and band set.",
    domain: "profile",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_profile_view_band_set",
    displayName: "Civil 3D Profile View Band Set",
    description: "Applies a band set style to an existing Civil 3D profile view, updating the data bands displayed above and below the grid.",
    domain: "profile",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface",
    displayName: "Civil 3D Surface",
    description: "Lists, inspects, analyzes, creates, and deletes surfaces.",
    domain: "surface",
    capabilities: ["query", "create", "delete", "analyze"],
    operations: ["list", "get", "get_elevation", "get_elevation_along", "get_statistics", "create", "delete"],
    pluginMethods: ["listSurfaces", "getSurface", "getSurfaceElevation", "getSurfaceElevationsAlong", "getSurfaceStatistics", "createSurface", "deleteSurface"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_edit",
    displayName: "Civil 3D Surface Edit",
    description: "Edits and analyzes surface definitions including points, breaklines, boundaries, contours, and volume.",
    domain: "surface",
    capabilities: ["edit", "analyze"],
    operations: ["add_points", "add_breakline", "add_boundary", "extract_contours", "compute_volume"],
    pluginMethods: ["addSurfacePoints", "addSurfaceBreakline", "addSurfaceBoundary", "extractSurfaceContours", "computeSurfaceVolume"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_drainage_workflow",
    displayName: "Civil 3D Surface Drainage Workflow",
    description: "Builds a structured drainage analysis by fetching a surface, tracing flow, sampling elevations, and estimating runoff.",
    domain: "hydrology",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["getSurface", "traceHydrologyFlowPath", "getSurfaceElevationsAlong", "estimateHydrologyRunoff"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_hydrology_watershed_runoff_workflow",
    displayName: "Civil 3D Hydrology Watershed Runoff Workflow",
    description: "Builds a complete watershed-to-runoff analysis by locating or using an outlet, delineating the watershed, calculating catchment area, converting area units, and estimating Rational Method runoff.",
    domain: "hydrology",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["findHydrologyLowPoint", "delineateWatershed", "calculateCatchmentArea", "estimateHydrologyRunoff"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_hydrology_runoff_detention_workflow",
    displayName: "Civil 3D Hydrology Runoff Detention Workflow",
    description: "Builds a runoff-to-detention workflow by estimating Rational Method runoff, sizing a detention basin, and optionally generating a stage-storage-discharge table.",
    domain: "hydrology",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["estimateHydrologyRunoff", "calculateDetentionBasinSize", "calculateDetentionStageStorage"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_hydrology_runoff_pipe_workflow",
    displayName: "Civil 3D Hydrology Runoff Pipe Workflow",
    description: "Builds a runoff-to-pipe-network workflow by estimating Rational Method runoff, then performing HGL and hydraulic capacity analysis on a gravity pipe network.",
    domain: "hydrology",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["estimateHydrologyRunoff", "calculatePipeNetworkHgl", "analyzePipeNetworkHydraulics"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_comparison_workflow",
    displayName: "Civil 3D Surface Comparison Workflow",
    description: "Builds a structured comparison between two surfaces and computes cut/fill volume differences.",
    domain: "surface",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["getSurface", "computeSurfaceVolume"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor",
    displayName: "Civil 3D Corridor",
    description: "Lists, inspects, rebuilds, and reads corridor surfaces and feature lines.",
    domain: "corridor",
    capabilities: ["query", "manage", "analyze"],
    operations: ["list", "get", "rebuild", "get_surfaces", "get_feature_lines", "compute_volumes"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor_summary",
    displayName: "Civil 3D Corridor Summary",
    description: "Builds a structured corridor summary from corridor detail, corridor surfaces, and optional volume analysis.",
    domain: "corridor",
    capabilities: ["query", "analyze", "generate"],
    pluginMethods: ["getCorridor", "getCorridorSurfaces", "computeCorridorVolumes"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor_target_mapping_get",
    displayName: "Civil 3D Corridor Target Mapping Get",
    description: "Retrieve the current subassembly target mappings for a Civil 3D corridor. Returns all target parameters for each baseline region — including daylight surfaces, width targets, slope targets, and alignment/profile targets.",
    domain: "corridor",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor_target_mapping_set",
    displayName: "Civil 3D Corridor Target Mapping Set",
    description: "Set or update subassembly target mappings on a Civil 3D corridor region. Assigns surfaces, alignments, profiles, or polylines as targets for subassembly parameters (e.g., daylight surface, lane width target). Rebuilds the corridor after applying.",
    domain: "corridor",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor_region_add",
    displayName: "Civil 3D Corridor Region Add",
    description: "Add a new region to a Civil 3D corridor baseline. Regions define which assembly applies over a station range and at what sampling frequency. Use to apply different assemblies in different parts of the corridor (e.g., full section on tangent, reduced section in cut).",
    domain: "corridor",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_corridor_region_delete",
    displayName: "Civil 3D Corridor Region Delete",
    description: "Delete a region from a Civil 3D corridor baseline by its zero-based index. Rebuilds the corridor after deletion.",
    domain: "corridor",
    capabilities: ["edit", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_section",
    displayName: "Civil 3D Section",
    description: "Lists sample line groups, gets section data, and creates sample lines.",
    domain: "section",
    capabilities: ["query", "create"],
    operations: ["list_sample_line_groups", "get_section_data", "create_sample_lines"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_section_view_create",
    displayName: "Civil 3D Section View Create",
    description: "Create Civil 3D section views for a sample line group. Places section view boxes in model space at the specified insertion point. Optionally applies a style, band set, and constrains to a station range.",
    domain: "section",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_section_view_list",
    displayName: "Civil 3D Section View List",
    description: "List Civil 3D section views in the active drawing. Optionally filter by alignment name and/or sample line group. Returns view handles, station ranges, and bounding box extents for each view.",
    domain: "section",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_section_view_update_style",
    displayName: "Civil 3D Section View Update Style",
    description: "Update the display style and/or band set style on existing Civil 3D section views for a sample line group. Use to batch-apply a new style after initial creation.",
    domain: "section",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_section_view_group_create",
    displayName: "Civil 3D Section View Group Create",
    description: "Create a Civil 3D section view group — a multi-row grid layout of section views for all stations in a sample line group. Supports custom row/column counts, spacing, and style assignment.",
    domain: "section",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_section_view_export",
    displayName: "Civil 3D Section View Export",
    description: "Export Civil 3D section data to a CSV or text file. Includes station, offset, and surface elevation data per section. Optionally includes corridor material breakdowns.",
    domain: "section",
    capabilities: ["query", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_point",
    displayName: "Civil 3D Point",
    description: "Lists, gets, creates, imports, and deletes COGO points and point groups.",
    domain: "point",
    capabilities: ["query", "create", "delete", "manage"],
    operations: ["list", "get", "create", "list_groups", "import", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "create_cogo_point",
    displayName: "Create COGO Point",
    description: "Creates COGO points in the current drawing.",
    domain: "point",
    capabilities: ["create"],
    pluginMethods: ["createCogoPoints"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_point_group_create",
    displayName: "Civil 3D Point Group Create",
    description: "Create a new Civil 3D point group with optional filter criteria. Point groups organize COGO points for display, export, and surface data operations.",
    domain: "point",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_point_group_update",
    displayName: "Civil 3D Point Group Update",
    description: "Update filter criteria and description of an existing Civil 3D point group.",
    domain: "point",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_point_group_delete",
    displayName: "Civil 3D Point Group Delete",
    description: "Delete a Civil 3D point group. This removes the group definition only — the COGO points themselves are not deleted.",
    domain: "point",
    capabilities: ["delete", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_point_export",
    displayName: "Civil 3D Point Export",
    description: "Export Civil 3D COGO points to a text/CSV format string. Supports PNEZD, PENZ, XYZD, XYZ, and CSV formats. Filter by group or specific point numbers.",
    domain: "point",
    capabilities: ["query", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_point_transform",
    displayName: "Civil 3D Point Transform",
    description: "Transform Civil 3D COGO points by translation, rotation, and/or scale. Apply to specific point numbers, a point group, or all points. Rotation is around the drawing origin.",
    domain: "point",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_cogo_inverse",
    displayName: "Civil 3D COGO Inverse",
    description: "Calculate the bearing and distance between two 2D coordinate pairs.",
    domain: "survey",
    capabilities: ["query", "analyze"],
    pluginMethods: ["cogoInverse"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_cogo_direction_distance",
    displayName: "Civil 3D COGO Direction Distance",
    description: "Project a new point from a starting coordinate using bearing, distance, and optional slope.",
    domain: "survey",
    capabilities: ["query", "analyze"],
    pluginMethods: ["cogoDirectionDistance"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_cogo_traverse",
    displayName: "Civil 3D COGO Traverse",
    description: "Solve a traverse from a starting point through a sequence of bearing and distance courses.",
    domain: "survey",
    capabilities: ["query", "analyze"],
    pluginMethods: ["cogoTraverse"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_cogo_curve_solve",
    displayName: "Civil 3D COGO Curve Solve",
    description: "Solve a horizontal curve from known curve elements and return the complete curve geometry.",
    domain: "survey",
    capabilities: ["query", "analyze"],
    pluginMethods: ["cogoCurveSolve"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "create_line_segment",
    displayName: "Create Line Segment",
    description: "Creates a line segment in the current drawing.",
    domain: "geometry",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "acad_create_polyline",
    displayName: "Create AutoCAD Polyline",
    description: "Creates a 2D polyline in model space.",
    domain: "geometry",
    capabilities: ["create"],
    pluginMethods: ["createPolyline"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "acad_create_3dpolyline",
    displayName: "Create AutoCAD 3D Polyline",
    description: "Creates a 3D polyline in model space.",
    domain: "geometry",
    capabilities: ["create"],
    pluginMethods: ["create3dPolyline"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "acad_create_text",
    displayName: "Create AutoCAD Text",
    description: "Creates DBText in model space.",
    domain: "labeling",
    capabilities: ["create"],
    pluginMethods: ["createText"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "acad_create_mtext",
    displayName: "Create AutoCAD MText",
    description: "Creates MText in model space.",
    domain: "labeling",
    capabilities: ["create"],
    pluginMethods: ["createMText"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_parcel",
    displayName: "Civil 3D Parcel",
    description: "Queries and manages parcel data.",
    domain: "parcel",
    capabilities: ["query", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_parcel_create",
    displayName: "Civil 3D Parcel Create",
    description: "Create a new Civil 3D parcel in a site by converting a closed polyline or feature line entity (via its handle), or by providing a vertex list. Optionally applies a parcel style and area label style.",
    domain: "parcel",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_parcel_edit",
    displayName: "Civil 3D Parcel Edit",
    description: "Edit properties of an existing Civil 3D parcel — rename it, change its display style, update its area label style, or attach a description. Does not modify parcel geometry.",
    domain: "parcel",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_parcel_lot_line_adjust",
    displayName: "Civil 3D Parcel Lot Line Adjust",
    description: "Adjust a parcel lot line to reach a target area. Civil 3D translates the specified shared lot-line segment until the parcel area converges to the target within tolerance. Useful for lot-area balancing in subdivision design.",
    domain: "parcel",
    capabilities: ["edit", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_parcel_report",
    displayName: "Civil 3D Parcel Report",
    description: "Generate a parcel area and dimension report for one or more parcels in a Civil 3D site. Returns parcel number, name, area, perimeter, and optional vertex coordinates. Can export to CSV.",
    domain: "parcel",
    capabilities: ["query", "generate", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_network",
    displayName: "Civil 3D Pipe Network",
    description: "Queries pipe network data.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_network_edit",
    displayName: "Civil 3D Pipe Network Edit",
    description: "Edits pipe network data.",
    domain: "pipe",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pipe_catalog",
    displayName: "Civil 3D Pipe Catalog",
    description: "Lists available pipe parts lists and part names to support gravity pipe network creation and editing.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    pluginMethods: ["listPipePartsCatalog"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_list",
    displayName: "Civil 3D Pressure Network List",
    description: "Lists all pressure networks in the active Civil 3D drawing with summary counts for pipes, fittings, and appurtenances.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_get_info",
    displayName: "Civil 3D Pressure Network Get Info",
    description: "Gets detailed information about a pressure network including its pipes, fittings, and appurtenances.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_create",
    displayName: "Civil 3D Pressure Network Create",
    description: "Creates a new pressure network in the active Civil 3D drawing.",
    domain: "pipe",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_delete",
    displayName: "Civil 3D Pressure Network Delete",
    description: "Deletes a pressure network and all its components from the drawing.",
    domain: "pipe",
    capabilities: ["delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_assign_parts_list",
    displayName: "Civil 3D Pressure Network Assign Parts List",
    description: "Assigns a parts list (pressure pipe catalog) to an existing pressure network.",
    domain: "pipe",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_set_cover",
    displayName: "Civil 3D Pressure Network Set Cover",
    description: "Sets the minimum cover depth for pipes in a pressure network.",
    domain: "pipe",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_validate",
    displayName: "Civil 3D Pressure Network Validate",
    description: "Validates a pressure network for cover violations, disconnected components, and parts catalog mismatches.",
    domain: "pipe",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_export",
    displayName: "Civil 3D Pressure Network Export",
    description: "Exports pressure network data as structured JSON including pipes, fittings, and appurtenances with full property details.",
    domain: "pipe",
    capabilities: ["query", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_network_connect",
    displayName: "Civil 3D Pressure Network Connect",
    description: "Connects two pressure networks by merging the source network into the target network.",
    domain: "pipe",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_pipe_add",
    displayName: "Civil 3D Pressure Pipe Add",
    description: "Adds a pressure pipe segment to an existing pressure network.",
    domain: "pipe",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_pipe_get_properties",
    displayName: "Civil 3D Pressure Pipe Get Properties",
    description: "Gets detailed properties of a specific pressure pipe including diameter, length, material, and cover depth.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_pipe_resize",
    displayName: "Civil 3D Pressure Pipe Resize",
    description: "Changes the size (part) of an existing pressure pipe to a different entry in the parts list.",
    domain: "pipe",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_fitting_add",
    displayName: "Civil 3D Pressure Fitting Add",
    description: "Adds a pressure fitting (elbow, tee, reducer, cap, etc.) to a pressure network at a specified location.",
    domain: "pipe",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_fitting_get_properties",
    displayName: "Civil 3D Pressure Fitting Get Properties",
    description: "Gets detailed properties of a specific pressure fitting including type, position, and part size.",
    domain: "pipe",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pressure_appurtenance_add",
    displayName: "Civil 3D Pressure Appurtenance Add",
    description: "Adds a pressure appurtenance (valve, hydrant, meter, air release valve, etc.) to a pressure network.",
    domain: "pipe",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_label",
    displayName: "Civil 3D Label",
    description: "Works with Civil 3D labels and annotation.",
    domain: "labeling",
    capabilities: ["query", "create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_coordinate_system",
    displayName: "Civil 3D Coordinate System",
    description: "Queries coordinate system information.",
    domain: "coordinate_system",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_data_shortcut",
    displayName: "Civil 3D Data Shortcut",
    description: "Works with Civil 3D data shortcuts.",
    domain: "data_shortcut",
    capabilities: ["query", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_data_shortcut_create",
    displayName: "Civil 3D Data Shortcut Create",
    description: "Publish a Civil 3D object (surface, alignment, profile, corridor, pipe network, or section view group) as a data shortcut so other drawings in the project can reference it without copying data. Writes a shortcut XML entry to the project's Data Shortcuts folder.",
    domain: "data_shortcut",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_data_shortcut_promote",
    displayName: "Civil 3D Data Shortcut Promote",
    description: "Promote a read-only data shortcut reference in the current drawing to a full, locally-editable Civil 3D object. The promoted object is independent of the source drawing and can be modified freely.",
    domain: "data_shortcut",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_data_shortcut_reference",
    displayName: "Civil 3D Data Shortcut Reference",
    description: "Reference an existing Civil 3D data shortcut from a project folder into the current drawing. Creates a live, read-only link to the source object that updates automatically when the source changes and you synchronize.",
    domain: "data_shortcut",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_data_shortcut_sync",
    displayName: "Civil 3D Data Shortcut Sync",
    description: "Synchronize outdated Civil 3D data shortcut references in the current drawing against their source objects. Detects which referenced objects have changed since last sync and updates them. Use dryRun=true to audit without modifying the drawing.",
    domain: "data_shortcut",
    capabilities: ["query", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_intersection_list",
    displayName: "Civil 3D Intersection List",
    description: "List all Civil 3D intersections in the active drawing. Returns name, main road alignment, intersecting road alignment, intersection point coordinates, and site membership for each intersection.",
    domain: "alignment",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_intersection_create",
    displayName: "Civil 3D Intersection Create",
    description: "Create a Civil 3D intersection between two road alignments. Computes or uses the supplied intersection point, applies curb return radii, and optionally creates corridor(s) for the intersection legs. Both alignments must have finished ground profiles.",
    domain: "alignment",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_intersection_get",
    displayName: "Civil 3D Intersection Get",
    description: "Get detailed properties of a Civil 3D intersection. Returns the main and intersecting road alignments, intersection point, offset distances, curb return configurations, and optionally corridor and curb return details.",
    domain: "alignment",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_superelevation_get",
    displayName: "Civil 3D Superelevation Get",
    description: "Retrieve the superelevation design data for a Civil 3D alignment. Returns design speed, attainment method, pivot point, and optionally the full station-by-station superelevation table.",
    domain: "alignment",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_superelevation_set",
    displayName: "Civil 3D Superelevation Set",
    description: "Apply superelevation design to a Civil 3D alignment using a specified design speed and AASHTO attainment method. Sets normal crown slope, pivot point, and calculates transition lengths automatically.",
    domain: "alignment",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_superelevation_design_check",
    displayName: "Civil 3D Superelevation Design Check",
    description: "Run a design check on a Civil 3D alignment's superelevation. Validates maximum superelevation rates and AASHTO attainment length requirements for the specified design speed. Returns pass/fail results with specific station violations.",
    domain: "alignment",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_superelevation_report",
    displayName: "Civil 3D Superelevation Report",
    description: "Generate a formatted superelevation report for a Civil 3D alignment. Includes attainment method, design speed, normal crown slope, transition lengths, and optional violation highlights. Writes to file or returns as string.",
    domain: "alignment",
    capabilities: ["query", "generate", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_assembly",
    displayName: "Civil 3D Assembly",
    description: "Lists and inspects assemblies and subassemblies.",
    domain: "assembly",
    capabilities: ["query", "inspect"],
    operations: ["list", "get"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_assembly_create",
    displayName: "Civil 3D Assembly Create",
    description: "Create a new Civil 3D assembly at a specified model-space location. Assemblies are corridor cross-section containers that hold subassemblies.",
    domain: "assembly",
    capabilities: ["create", "manage"],
    pluginMethods: ["createAssembly"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_subassembly_create",
    displayName: "Civil 3D Subassembly Create",
    description: "Add a subassembly from the Civil 3D catalog to an existing assembly, including lane, shoulder, ditch, and daylight components.",
    domain: "assembly",
    capabilities: ["create", "edit"],
    pluginMethods: ["createSubassembly"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_assembly_edit",
    displayName: "Civil 3D Assembly Edit",
    description: "Inspect or modify an existing Civil 3D assembly, including subassembly parameter edits and deletion.",
    domain: "assembly",
    capabilities: ["inspect", "edit", "manage"],
    pluginMethods: ["editAssembly"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_feature_line",
    displayName: "Civil 3D Feature Line",
    description: "Lists feature lines and exports them as 3D polylines.",
    domain: "feature_line",
    capabilities: ["query", "create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_list",
    displayName: "Civil 3D Grading Group List",
    description: "List all Civil 3D grading groups in the drawing. Returns name, handle, grading count, and validity status.",
    domain: "grading",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_get",
    displayName: "Civil 3D Grading Group Get",
    description: "Get detailed information about a Civil 3D grading group including cut/fill volumes and all contained gradings.",
    domain: "grading",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_create",
    displayName: "Civil 3D Grading Group Create",
    description: "Create a new Civil 3D grading group. Grading groups are containers for grading objects within a site.",
    domain: "grading",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_delete",
    displayName: "Civil 3D Grading Group Delete",
    description: "Delete a Civil 3D grading group and all its contained gradings.",
    domain: "grading",
    capabilities: ["delete", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_volume",
    displayName: "Civil 3D Grading Group Volume",
    description: "Get cut and fill volume report for a Civil 3D grading group. Returns cut volume, fill volume, and net volume.",
    domain: "grading",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_group_surface_create",
    displayName: "Civil 3D Grading Group Surface Create",
    description: "Create a Civil 3D surface from a grading group. The surface will represent the graded terrain.",
    domain: "grading",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_list",
    displayName: "Civil 3D Grading List",
    description: "List all grading objects within a specific Civil 3D grading group.",
    domain: "grading",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_get",
    displayName: "Civil 3D Grading Get",
    description: "Get detailed properties of a specific grading object including criteria, side, and volumes.",
    domain: "grading",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_create",
    displayName: "Civil 3D Grading Create",
    description: "Create a new Civil 3D grading from a feature line. The grading will project from the feature line using the specified criteria.",
    domain: "grading",
    capabilities: ["create", "edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_delete",
    displayName: "Civil 3D Grading Delete",
    description: "Delete a grading object from a Civil 3D grading group by its handle.",
    domain: "grading",
    capabilities: ["edit", "delete"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_grading_criteria_list",
    displayName: "Civil 3D Grading Criteria List",
    description: "List all available Civil 3D grading criteria sets and their individual criteria. Use criteria names when creating gradings.",
    domain: "grading",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_feature_line_create",
    displayName: "Civil 3D Feature Line Create",
    description: "Create a new Civil 3D feature line from an ordered list of 3D points. Feature lines are used as grading footprints and site design baselines.",
    domain: "grading",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_style",
    displayName: "Civil 3D Style",
    description: "Queries available Civil 3D styles.",
    domain: "style",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_job",
    displayName: "Civil 3D Job",
    description: "Inspects and manages background job state.",
    domain: "job",
    capabilities: ["query", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_alignment",
    displayName: "Civil 3D QC Check Alignment",
    description: "Run QC checks on a Civil 3D alignment. Validates tangent lengths, horizontal curve radii, spiral transitions, and design-speed compliance. Returns an array of violation findings.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_profile",
    displayName: "Civil 3D QC Check Profile",
    description: "Run QC checks on a Civil 3D profile. Validates maximum grade, minimum K-values for vertical curves, and sight distance requirements. Returns grade, K-value, and sight distance violations.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_corridor",
    displayName: "Civil 3D QC Check Corridor",
    description: "Run QC checks on a Civil 3D corridor. Identifies invalid regions, missing or unresolved targets, assembly gaps, and rebuild errors.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_pipe_network",
    displayName: "Civil 3D QC Check Pipe Network",
    description: "Run QC checks on a Civil 3D pipe network. Validates cover depth, pipe slope, flow velocity, structure connectivity, and sump depth. Returns violations per pipe and structure.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_surface",
    displayName: "Civil 3D QC Check Surface",
    description: "Run QC checks on a Civil 3D TIN surface. Detects elevation spikes, flat/suspect triangles, crossing breaklines, and data voids. Returns flagged point and triangle locations.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_labels",
    displayName: "Civil 3D QC Check Labels",
    description: "Check Civil 3D labels across one or all object types for missing labels and style standard violations. Returns a list of objects with label issues.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_report_generate",
    displayName: "Civil 3D QC Report Generate",
    description: "Run a full QC pass over the active drawing and write a consolidated report to disk (.txt or .csv). Covers alignments, profiles, corridors, pipe networks, surfaces, and labels. Returns the output file path and a summary of total findings.",
    domain: "qc",
    capabilities: ["query", "generate", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_check_drawing_standards",
    displayName: "Civil 3D QC Check Drawing Standards",
    description: "Audit the active Civil 3D drawing against CAD standards. Checks layer naming conventions, lineweights, and colors. Returns non-conforming objects grouped by violation type.",
    domain: "qc",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qc_fix_drawing_standards",
    displayName: "Civil 3D QC Fix Drawing Standards",
    description: "Automatically remediate drawing-standard layer issues by normalizing prefixes, replacing spaces, truncating overlong names, and optionally standardizing layer color and lineweight settings.",
    domain: "qc",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_corridor_volumes",
    displayName: "Civil 3D Quantity Corridor Volumes",
    description: "Calculate subassembly material volumes by region for a Civil 3D corridor. Optionally filter by material name and station range.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_surface_volume",
    displayName: "Civil 3D Quantity Surface Volume",
    description: "Calculate cut/fill volumes between two Civil 3D surfaces for quantity takeoff purposes. Optionally restrict the calculation to corridor extents or a polygon region.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_pipe_network_lengths",
    displayName: "Civil 3D Quantity Pipe Network Lengths",
    description: "Summarize total pipe lengths for a Civil 3D gravity pipe network. Optionally group results by pipe size and/or material.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_pressure_network_lengths",
    displayName: "Civil 3D Quantity Pressure Network Lengths",
    description: "Summarize total pipe lengths for a Civil 3D pressure network. Optionally group results by pipe size and/or material.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_parcel_areas",
    displayName: "Civil 3D Quantity Parcel Areas",
    description: "List area, perimeter, and address data for Civil 3D parcels. Filter by site and/or specific parcel names.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_alignment_lengths",
    displayName: "Civil 3D Quantity Alignment Lengths",
    description: "Return the total length (and optional station range sub-length) for one or more Civil 3D alignments.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_point_count_by_group",
    displayName: "Civil 3D Quantity Point Count By Group",
    description: "Count COGO points per point group in the Civil 3D drawing. Returns a summary table of group name and point count.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_export_to_csv",
    displayName: "Civil 3D Quantity Export To CSV",
    description: "Export a consolidated quantity takeoff report to a CSV file. Select which quantity categories to include and supply any required source object names.",
    domain: "quantity_takeoff",
    capabilities: ["query", "export"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_material_list_get",
    displayName: "Civil 3D Quantity Material List Get",
    description: "Retrieve the material list defined on a Civil 3D corridor. Optionally include pre-calculated quantities for each material.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_qty_earthwork_summary",
    displayName: "Civil 3D Quantity Earthwork Summary",
    description: "Generate a running earthwork cut/fill summary table between a base and design surface. Optionally scoped to an alignment corridor with configurable station interval.",
    domain: "quantity_takeoff",
    capabilities: ["query", "analyze", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_database_list",
    displayName: "Civil 3D Survey Database List",
    description: "List Civil 3D survey databases associated with the current drawing.",
    domain: "survey",
    capabilities: ["query", "inspect"],
    pluginMethods: ["listSurveyDatabases"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_database_create",
    displayName: "Civil 3D Survey Database Create",
    description: "Create a new Civil 3D survey database for observations, figures, and survey networks.",
    domain: "survey",
    capabilities: ["create", "manage"],
    pluginMethods: ["createSurveyDatabase"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_figure_list",
    displayName: "Civil 3D Survey Figure List",
    description: "List survey figures stored in Civil 3D survey databases.",
    domain: "survey",
    capabilities: ["query", "inspect"],
    pluginMethods: ["listSurveyFigures"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_figure_get",
    displayName: "Civil 3D Survey Figure Get",
    description: "Get detailed geometry and vertices for a specific Civil 3D survey figure.",
    domain: "survey",
    capabilities: ["query", "inspect"],
    pluginMethods: ["getSurveyFigure"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_observation_list",
    displayName: "Civil 3D Survey Observation List",
    description: "List raw field-book observations stored in a Civil 3D survey database. Returns angle, distance, and direction observations grouped by survey network. Use to inspect raw data before running a network adjustment.",
    domain: "survey",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_network_adjust",
    displayName: "Civil 3D Survey Network Adjust",
    description: "Perform a traverse or least-squares adjustment on a Civil 3D survey network. Distributes angular and linear closure errors across the traverse, optionally writing adjusted coordinates back to the database. Call with applyAdjustment=false first to preview the closure error.",
    domain: "survey",
    capabilities: ["analyze", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_figure_create",
    displayName: "Civil 3D Survey Figure Create",
    description: "Create a new survey figure in a Civil 3D survey database by connecting existing survey points in order. Survey figures represent topographic features observed in the field (e.g., toe of slope, edge of pavement, fence line).",
    domain: "survey",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_survey_landxml_import",
    displayName: "Civil 3D Survey LandXML Import",
    description: "Import survey data from a LandXML file into a Civil 3D survey database and/or drawing. Supports importing COGO points, alignments, and TIN surfaces. Handles coordinate system mapping and duplicate point policies.",
    domain: "survey",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_set_list",
    displayName: "Civil 3D Sheet Set List",
    description: "Lists all Plan Production sheet sets in the active Civil 3D drawing.",
    domain: "plan_production",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_set_get_info",
    displayName: "Civil 3D Sheet Set Get Info",
    description: "Gets detailed information about a Plan Production sheet set including all sheets.",
    domain: "plan_production",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_set_create",
    displayName: "Civil 3D Sheet Set Create",
    description: "Creates a new Plan Production sheet set in the active Civil 3D drawing.",
    domain: "plan_production",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_add",
    displayName: "Civil 3D Sheet Add",
    description: "Adds a new sheet to an existing Plan Production sheet set.",
    domain: "plan_production",
    capabilities: ["create", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_get_properties",
    displayName: "Civil 3D Sheet Get Properties",
    description: "Gets full properties of a specific sheet within a Plan Production sheet set.",
    domain: "plan_production",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_set_title_block",
    displayName: "Civil 3D Sheet Set Title Block",
    description: "Sets or updates the title block template on a sheet within a Plan Production sheet set.",
    domain: "plan_production",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_plan_profile_sheet_create",
    displayName: "Civil 3D Plan Profile Sheet Create",
    description: "Creates a Plan/Profile sheet for a given alignment and profile using Civil 3D's AeccPlanProductionHelper.",
    domain: "plan_production",
    capabilities: ["create", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_plan_profile_sheet_update_alignment",
    displayName: "Civil 3D Plan Profile Sheet Update Alignment",
    description: "Updates the alignment and optionally the profile on an existing Plan/Profile sheet.",
    domain: "plan_production",
    capabilities: ["edit", "manage"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_view_create",
    displayName: "Civil 3D Sheet View Create",
    description: "Creates a viewport/view on a sheet layout in the active Civil 3D drawing.",
    domain: "plan_production",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_view_set_scale",
    displayName: "Civil 3D Sheet View Set Scale",
    description: "Updates the scale of a viewport on a sheet layout.",
    domain: "plan_production",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_publish_pdf",
    displayName: "Civil 3D Sheet Publish PDF",
    description: "Publishes one or more sheet layouts to a PDF file using AutoCAD's PlotEngine.",
    domain: "plan_production",
    capabilities: ["export", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sheet_set_export",
    displayName: "Civil 3D Sheet Set Export",
    description: "Exports all sheets in a Plan Production sheet set to a single multi-page PDF.",
    domain: "plan_production",
    capabilities: ["export", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_volume_calculate",
    displayName: "Civil 3D Surface Volume Calculate",
    description: "Calculate cut/fill volumes between two Civil 3D surfaces. Returns cut volume, fill volume, net volume, and areas.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_volume_report",
    displayName: "Civil 3D Surface Volume Report",
    description: "Generate a formatted volume report comparing two Civil 3D surfaces. Returns a human-readable report with cut/fill summary.",
    domain: "surface",
    capabilities: ["query", "analyze", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_volume_by_region",
    displayName: "Civil 3D Surface Volume By Region",
    description: "Calculate cut/fill volumes between two surfaces within a specific polygon region boundary.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_analyze_slope",
    displayName: "Civil 3D Surface Analyze Slope",
    description: "Analyze slope distribution across a Civil 3D surface. Returns area and percentage for each slope range.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_analyze_elevation",
    displayName: "Civil 3D Surface Analyze Elevation",
    description: "Analyze elevation band distribution across a Civil 3D surface. Returns area and percentage for each elevation range.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_analyze_directions",
    displayName: "Civil 3D Surface Analyze Directions",
    description: "Analyze surface aspect/facing direction distribution. Returns area breakdown by cardinal/intercardinal direction sectors.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_watershed_add",
    displayName: "Civil 3D Surface Watershed Add",
    description: "Add watershed analysis to a Civil 3D surface. Identifies drainage basins and flow paths.",
    domain: "surface",
    capabilities: ["edit", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_contour_interval_set",
    displayName: "Civil 3D Surface Contour Interval Set",
    description: "Set the minor and major contour display intervals for a Civil 3D surface.",
    domain: "surface",
    capabilities: ["edit"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_statistics_get",
    displayName: "Civil 3D Surface Statistics Get",
    description: "Get comprehensive statistics for a Civil 3D surface including elevation range, area, point count, and triangle count.",
    domain: "surface",
    capabilities: ["query", "inspect", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_sample_elevations",
    displayName: "Civil 3D Surface Sample Elevations",
    description: "Sample surface elevations at grid points, discrete points, or along a transect line.",
    domain: "surface",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_surface_create_from_dem",
    displayName: "Civil 3D Surface Create From DEM",
    description: "Create a Civil 3D TIN surface by importing a DEM file (.dem, .tif, .asc, .flt, etc.).",
    domain: "surface",
    capabilities: ["create"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_sight_distance_calculate",
    displayName: "Civil 3D Sight Distance Calculate",
    description: "Calculate AASHTO stopping sight distance (SSD), passing sight distance (PSD), or decision sight distance (DSD) for a given design speed and grade. Returns required sight distance in feet and meters, the minimum K-value for vertical curves, and the corresponding crest/sag curve parameters. Optionally checks the available sight distance at a specific station on a Civil 3D alignment/profile.",
    domain: "sight_distance",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_stopping_distance_check",
    displayName: "Civil 3D Stopping Distance Check",
    description: "Check stopping sight distance (SSD) compliance along an entire Civil 3D alignment and profile at a specified station interval. Returns a table of stations where the available SSD falls below the required SSD for the design speed.",
    domain: "sight_distance",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_detention_basin_size_calculate",
    displayName: "Civil 3D Detention Basin Size Calculate",
    description: "Size a detention basin to reduce peak stormwater runoff. Returns required storage volume, estimated basin dimensions, outlet size, and freeboard recommendation.",
    domain: "detention",
    capabilities: ["query", "analyze", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_detention_stage_storage",
    displayName: "Civil 3D Detention Stage Storage",
    description: "Generate a stage-storage-discharge table for a Civil 3D detention basin surface.",
    domain: "detention",
    capabilities: ["query", "analyze", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_slope_geometry_calculate",
    displayName: "Civil 3D Slope Geometry Calculate",
    description: "Calculate daylight line coordinates and slope geometry for cut and fill sections along a Civil 3D alignment.",
    domain: "slope_analysis",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_slope_stability_check",
    displayName: "Civil 3D Slope Stability Check",
    description: "Evaluate cut and fill slope stability along a Civil 3D alignment, flagging stations where slopes exceed allowable limits.",
    domain: "slope_analysis",
    capabilities: ["query", "analyze"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_pay_items_export",
    displayName: "Civil 3D Pay Items Export",
    description: "Extract Civil 3D quantities and export them as a structured pay item schedule to CSV or Excel.",
    domain: "cost_estimation",
    capabilities: ["query", "export", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_material_cost_estimate",
    displayName: "Civil 3D Material Cost Estimate",
    description: "Generate a construction cost estimate by combining Civil 3D quantities with user-provided unit prices.",
    domain: "cost_estimation",
    capabilities: ["query", "analyze", "generate"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
  {
    toolName: "civil3d_orchestrate",
    displayName: "Civil 3D Orchestrate",
    description: "Plans a Civil 3D request by selecting an intent, inferring parameters from context, and identifying missing prerequisites before execution.",
    domain: "docs",
    capabilities: ["query", "inspect", "generate"],
    operations: ["plan", "execute"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_standards_lookup",
    displayName: "Civil 3D Standards Lookup",
    description: "Searches extracted Framework standards guidance for layers, styles, templates, labeling, plotting, and textstyle conventions.",
    domain: "docs",
    capabilities: ["query", "inspect"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_hydrology",
    displayName: "Civil 3D Hydrology",
    description: "Provides hydrology-oriented capability discovery, surface-based flow path tracing, low-point search, and runoff estimation.",
    domain: "hydrology",
    capabilities: ["query", "analyze"],
    operations: ["list_capabilities", "trace_flow_path", "find_low_point", "estimate_runoff", "delineate_watershed", "calculate_catchment_area"],
    pluginMethods: ["listHydrologyCapabilities", "traceHydrologyFlowPath", "findHydrologyLowPoint", "estimateHydrologyRunoff", "delineateWatershed", "calculateCatchmentArea"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_catchment",
    displayName: "Civil 3D Catchment Management",
    description: "Manages Civil 3D catchments and catchment groups: list groups, list/get/edit catchment properties (runoff coefficient, Manning's n, curve number, Tc), copy catchments between groups, retrieve flow paths and boundaries.",
    domain: "catchment",
    capabilities: ["query", "inspect", "edit"],
    operations: ["list_catchment_groups", "get_catchment_group", "list_catchments", "get_catchment_properties", "set_catchment_properties", "copy_catchment_to_group", "get_catchment_flow_path", "get_catchment_boundary"],
    pluginMethods: ["listCatchmentGroups", "getCatchmentGroup", "listCatchments", "getCatchmentProperties", "setCatchmentProperties", "copyCatchmentToGroup", "getCatchmentFlowPath", "getCatchmentBoundary"],
    requiresActiveDrawing: true,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_time_of_concentration",
    displayName: "Civil 3D Time of Concentration & Hydrograph",
    description: "Calculates Time of Concentration using Kirpich, TR-55 (sheet/shallow/channel), FAA, and NRCS Lag methods. Generates SCS triangular and curvilinear unit hydrographs with peak flow and ordinate tables.",
    domain: "hydrology",
    capabilities: ["query", "analyze", "generate"],
    operations: ["list_tc_methods", "calculate_tc", "generate_hydrograph"],
    pluginMethods: ["listTcMethods", "calculateTimeOfConcentration", "generateHydrograph"],
    requiresActiveDrawing: false,
    safeForRetry: true,
    status: "implemented",
  },
  {
    toolName: "civil3d_stm",
    displayName: "Civil 3D Storm & Sanitary Analysis (STM)",
    description: "Manages Storm and Sanitary Analysis workflows: export pipe network/catchment data to Hydraflow .STM files, import SSA results back into Civil 3D, and open gravity network analysis. Note: export/import open dialogs requiring user interaction.",
    domain: "stm",
    capabilities: ["query", "export", "import"],
    operations: ["list_ssa_capabilities", "export_stm", "import_stm", "open_storm_sanitary_analysis"],
    pluginMethods: ["listSsaCapabilities", "exportStm", "importStm", "openStormSanitaryAnalysis"],
    requiresActiveDrawing: true,
    safeForRetry: false,
    status: "implemented",
  },
];

export function listToolCatalog() {
  return TOOL_CATALOG;
}

export function listDomains() {
  return [...new Set(TOOL_CATALOG.map((entry) => entry.domain))].sort();
}
